### PR TITLE
Update composer.json to allow php7

### PR DESCRIPTION
**Pull request by erik-zicht**

### CODE REVIEW

**Review by muhammedeminakbulut — APPROVED** [review]

**Review by pbergman — CHANGES_REQUESTED** [review]
prefer to new branch to drop BC

**Comment by erik-zicht** [comment]
PR updated

**Comment by erik-zicht** [comment]
Er faalt een test, die kan ik lokaal reproduceren, zal dit zsm fixen.

**Comment by boudewijn-zicht** [comment]
Woops, did not see erik's last comment.  Will not delete the branch so the test can still be fixed.

**Pull request merged**
